## servlet configuration
server:
  port: ${PORT:8084}

## application configuration
spring:
  application:
    name: ${APPLICATION_NAME:ignite-reporting-service}
  datasource:
    url: jdbc:mysql://db_instance:db_port/ignite_reporting_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:db_username}
    password: ${DB_PASSWORD:db_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

## eureka server configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery_instance:8761/eureka}

# oauth2 security configuration
security:
  oauth2:
    resource:
      token-info-uri: http://gateway_instance:8080/ignite-auth-service/oauth/check_token
    client:
      client-id: ignite-client
      client-secret: 1234

# oauth2 resource server configuration
oauth:
  resource-id: ${RESOURCE_ID:ignite_report}

## Student-Microservice
student:
  baseUrl: ${REGISTRATION_BASE_URL:http://gateway_instance:8080/ignite-student-service}
  studentInfoUrl: /api/v1/student/get/{studentId}

## Tuition-Microservice
tuition:
  baseUrl: ${TUITION_BASE_URL:http://gateway_instance:8080/ignite-tuition-service}
  tuitionListUrl: /api/v1/tuition/get/all

## Payment-Microservice
payment:
  baseUrl: ${PAYMENT_BASE_URL:http://gateway_instance:8080/ignite-payment-service}
  paidStudentsInfoUrl: /api/v1/payment/get/all/{tuitionId}/{month}
