## servlet configuration
server:
  port: ${PORT:8084}

## application configuration
spring:
  application:
    name: ${APPLICATION_NAME:ignite-reporting-service}
  datasource:
    url: jdbc:mysql://localhost:3306/reporting_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  ## configure active profiles
  profiles:
    active: prod

## eureka server configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

## Registration-Microservice
registration:
  baseUrl: ${REGISTRATION_BASE_URL:http://localhost:8082}
  tuitionListUrl: /api/v1/tuition/get/all
  studentInfoUrl: /api/v1/student/get/{studentId}

## Payment-Microservice
payment:
  baseUrl: ${PAYMENT_BASE_URL:http://localhost:8083}
  paidStudentsInfoUrl: /api/v1/payment/get/all/{tuitionId}/{month}

